name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [1.2.14] # only 1.2.x is supported by nim-eth at the moment
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: nim-dagger-contracts
    - name: Checkout dagger-contracts
      uses: actions/checkout@v2
      with:
        repository: status-im/dagger-contracts
        path: dagger-contracts
    - name: Install Nim
      uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nim }}
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dagger-contracts
      working-directory: dagger-contracts
      run: npm install
    - name: Run dagger-contracts test node
      working-directory: dagger-contracts
      run: |
        # https://github.com/wighawag/hardhat-deploy/issues/168#issuecomment-919096130
        npx hardhat node --no-deploy &
        sleep 3
        npx hardhat deploy --network localhost --export 'deployment-localhost.json'
    - name: Build
      working-directory: nim-dagger-contracts
      run: nimble install -y
    - name: Test
      working-directory: nim-dagger-contracts
      run: nimble test -y
